[build]
  command = "bundle install && bundle exec jekyll build --config _config.yml,_config_netlify.yml"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"
